version: '3'

services:
  eventeum1:
    build: ./
    ports:
    - "8060:8060"
    depends_on:
      - parity
      - mongodb
      - kafka
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      ETHEREUM_NODE_URL: http://eth-node:8545
      ZOOKEEPER_ADDRESS: zookeeper:2181
      KAFKA_ADDRESSES: kafka:19092
      BROADCASTER_MULTIINSTANCE: "true"
    networks:
      - default

  eventeum2:
      build: ./
      ports:
      - "8050:8050"
      depends_on:
        - parity
        - mongodb
        - kafka
        - eventeum1
      environment:
        SERVER_PORT: 8050
        SPRING_DATA_MONGODB_HOST: mongodb
        ETHEREUM_NODE_URL: http://eth-node:8545
        ZOOKEEPER_ADDRESS: zookeeper:2181
        KAFKA_ADDRESSES: kafka:19092
        BROADCASTER_MULTIINSTANCE: "true"
      networks:
        - default

  parity:
    build:
      context: .
      dockerfile: Dockerfile-ParityNode
    ports:
      - "8545:8545"
      - "8180:8180"
      - "8546:8546"
    volumes:
      - $HOME/parity/data:/root/.local/share/io.parity.ethereum
      - $HOME/parity/log:/data/parity-logs
    tty: true
    networks:
      default:
        aliases:
          - eth-node

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - $HOME/mongodb/data/db:/data/db
    networks:
      - default

  zookeeper:
      image: confluentinc/cp-zookeeper:5.0.1-1
      ports:
        - "2181:2181"
      environment:
        zk_id: "1"
        ZOOKEEPER_CLIENT_PORT: 2181
      networks:
        - default

  kafka:
    image: confluentinc/cp-kafka:5.0.1-1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - default